[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "filehashcache"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "A simple file-based caching system using hash-based file names"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/filehashcache"
"Bug Tracker" = "https://github.com/yourusername/filehashcache/issues"

[tool.setuptools]
py-modules = ["filehashcache"]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["."]

[project.scripts]
test = "pytest:main"