[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "filehashcache"
dynamic = ["version"]
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "A simple file-based caching system using hash-based file names"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["jsonpickle", "numpy", "pandas"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.dynamic]
version = {attr = "filehashcache.__version__"}

[project.urls]
"Homepage" = "https://github.com/yourusername/filehashcache"
"Bug Tracker" = "https://github.com/yourusername/filehashcache/issues"

[project.optional-dependencies]
extra = ["pandas", "ipython", "tqdm", "orjson"]
dev = ["pandas", "setuptools-scm", "ipython"]
test = ["pytest"]

[tool.setuptools]
py-modules = ["filehashcache"]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["."]

[project.scripts]
test = "pytest:main"